baseURL = 'https://example.org/'
languageCode = 'ru'
title = 'YA Cosmetologist'
publishDir = 'public'
disableKinds = ['taxonomy', 'term', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
